"Load the typed kernel"

"Loading Kernel-Objects package"
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Objects\ProtoObject.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Objects\Object.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Objects\TUndefinedObject.st') fileIn.

(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Objects\Boolean.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Objects\True.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Objects\False.st') fileIn.

"Loading Kernel-Methods package"
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Methods\BlockClosure.st') fileIn.

"Loading Kernel-Numbers package"
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Numbers\Magnitude.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Numbers\Number.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Numbers\Integer.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Numbers\SmallInteger.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Numbers\LargePositiveInteger.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Numbers\LargeNegativeInteger.st') fileIn.

"Loading Kernel-Classes package"
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Classes\Behavior.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Classes\ClassDescription.st') fileIn.
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Kernel-Classes\Class.st') fileIn.

"Loading Collections-Abstract package"
(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Collections-Abstract\Collection.st') fileIn.
"(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Collections-Abstract\SequenceableCollection.st') fileIn."
"(FileStream oldFileNamed: '..\scripts\Typesystem\Source-TypedKernel\Collections-Abstract\ArrayedCollection.st') fileIn."





