Deprecation raiseWarning: false.
Author fullName: 'hudson'.


Gofer new
squeaksource: 'SmallDude';
package: 'ConfigurationOfSmallDude';
load.
(Smalltalk globals at: #ConfigurationOfSmallDude) loadDefault.



Gofer new
squeaksource: 'Arki';
package: 'ConfigurationOfMenssana';
load.
((Smalltalk globals at: #ConfigurationOfMenssana) project version: '1.0') load.


Gofer new
squeaksource: 'Fame';
package: 'Fame';
load.



